/* Generated by Koha Plugin Generator https://kohaplugin.nuantio.com/ */
$(document).ready( function() {

if ($('body[id^="main_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="circ_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/circulation" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="pat_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/patrons" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="catalog_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/search" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('#lists_shelves').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/lists" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="cat_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/cataloging" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="acq_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/acquisitions" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="auth_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/authorities" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="ser_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/serials" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="courses_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/course-reserves" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="rep_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/reports" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="tools_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/tools" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="admin_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/administration" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('body[id^="erm_"]').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/e-resource-management" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}

if ($('#payments').length) {
	$('#shortcut').append('<div><a class href="https://help.bywatersolutions.com/portal/en/kb/products/koha/modules/point-of-sale" id="helper" target="_blank"><i class="fa-brands fa-readme"></i><span>ByWater Help</span></a></div>');
}
  
});